In [4]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)


Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

Question 1: Array Dimensions The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data Shape of sales_data Total number of values Data type of the array Memory occupied by the array


In [30]:
import numpy as np
print("no of dimensions:",sales_data.ndim)
print("shape of sales data:",sales_data.shape)
print("total no of values:",sales_data.size)
print("data type of the array:",sales_data.dtype)
print("memory occupied:",sales_data.nbytes,"bytes")

no of dimensions: 2
shape of sales data: (5, 6)
total no of values: 30
data type of the array: int64
memory occupied: 240 bytes


Question 2: Store and Category Count Calculate the following:

Total number of stores Total number of product categories Total number of store-category combinations

In [41]:
import numpy as np
print("total no of stores:",stores.size)
print("total no of product categories:",categories.size)
print("total no of store-category combinations:",stores.size*categories.size)

total no of stores: 5
total no of product categories: 6
total no of store-category combinations: 30


Question 3: Sales Data Type Conversion The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32 float64 Compare the memory used by both arrays.

In [48]:
sales_float32=sales_data.astype(np.float32)
sales_float64=sales_data.astype(np.float64)
print("memory used sales data float32:",sales_float64.nbytes,"bytes")
print("memory used sales_data float64:",sales_float32.nbytes,"nbytes")
print("sales data float32:",sales_float32.dtype)
print("sales_data float64:",sales_float64.dtype)

memory used sales data float32: 240 bytes
memory used sales_data float64: 120 nbytes
sales data float32: float32
sales_data float64: float64


Part 3: Indexing and Data Extraction

Question 4: Bengaluru Store Analysis The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [49]:
print("sales for bengaluru:",sales_data[0])

sales for bengaluru: [850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis Extract the total cost incurred by the Mumbai store for all product categories.

In [50]:
print(np.sum(sales_data[3]))

2820000


Question 6: Electronics Sales Across Stores The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [51]:
print(sales_data[:,0])

[ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores Extract the Clothing cost for every store from cost_data

In [52]:
print(cost_data[:,2])

[220000 210000 245000 265000 205000]


Question 8: Hyderabad Furniture Performance Find the following for Hyderabad:

Furniture sales Furniture cost Furniture profit

In [53]:
print("furniture sales:",sales_data[1,3])
print("furniture cost:",cost_data[1,3])
print("profit:",sales_data[1,3]-cost_data[1,3])

furniture sales: 310000
furniture cost: 225000
profit: 85000


Question 9: Chennai Category Range Extract Chennai’s sales for the following categories:

Groceries Clothing Furniture Use array slicing.

In [54]:
print("chennai sales on groceries:",sales_data[2,1],)
print("clothing:",sales_data[2,2])
print("furnitute:",sales_data[2,3])

chennai sales on groceries: 390000
clothing: 340000
furnitute: 260000


Question 10: Selected Store Analysis Extract sales data for:

Bengaluru Chennai Pune Include only:

Electronics Clothing Beauty Use advanced indexing.

In [55]:
print("bengaluru sales on electronics:",sales_data[0,0])
print("bengaluru sales on clothing:",sales_data[0,2])
print("bengaluru sales on beauty:",sales_data[0,4])
print("chennai sales on electronics:",sales_data[2,0])
print("chennai sales on clothing:",sales_data[2,2])
print("chennai sales on beauty:",sales_data[2,4])
print("pune sales on electronics:",sales_data[4,0])
print("pune sales on clothing:",sales_data[4,2])
print("pune sales on beauty:",sales_data[4,4])


bengaluru sales on electronics: 850000
bengaluru sales on clothing: 310000
bengaluru sales on beauty: 190000
chennai sales on electronics: 920000
chennai sales on clothing: 340000
chennai sales on beauty: 185000
pune sales on electronics: 690000
pune sales on clothing: 280000
pune sales on beauty: 175000


Part 4: Sales Aggregation

Question 11: Company-Wide Sales Calculate the total sales revenue generated by all stores and all categories.

In [69]:
print(np.sum(sales_data))

11675000


Question 12: Store-Wise Sales Calculate total sales revenue for each store.

Display the result together with the store names.

In [81]:
print("bengaluru total sales:",np.sum(sales_data[0]))
print("hyderabad total sales:",np.sum(sales_data[1]))
print("chennai total sales:",np.sum(sales_data[2]))
print("mumbai total sales:",np.sum(sales_data[3]))
print("pune total sales:",np.sum(sales_data[4]))

bengaluru total sales: 2270000
hyderabad total sales: 2295000
chennai total sales: 2310000
mumbai total sales: 2820000
pune total sales: 1980000


Question 13: Category-Wise Sales Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [86]:
print(" electronics total sales:",np.sum(sales_data[:,0]))
print("groceries total sales:",np.sum(sales_data[:,1]))
print("clothing  total sales:",np.sum(sales_data[:,2]))
print("furniture total sales:",np.sum(sales_data[:,3]))
print("beauty total sales:",np.sum(sales_data[:,4]))
print("sports total sales:",np.sum(sales_data[:,5]))

 electronics total sales: 4290000
groceries total sales: 2185000
clothing  total sales: 1600000
furniture total sales: 1415000
beauty total sales: 1010000
sports total sales: 1175000


Question 14: Average Sales Per Store Calculate the average sales generated by each store across all six product categories.

In [100]:
print(sum(sales_data[0]/sales_data[0].size))
print(sum(sales_data[1]/sales_data[1].size))
print(sum(sales_data[2]/sales_data[2].size))
print(sum(sales_data[3]/sales_data[3].size))
print(sum(sales_data[4]/sales_data[4].size))

378333.3333333333
382500.0
384999.99999999994
470000.0
330000.0


Question 15: Average Sales Per Category Calculate the average sales of each product category across the five stores

In [123]:
print(" electronics total sales:",np.sum(sales_data[:,0]/sales_data[:,0].size))
print("groceries total sales:",np.sum(sales_data[:,1]/sales_data[:,1].size))
print("clothing  total sales:",np.sum(sales_data[:,2]/sales_data[:,2].size))
print("furniture total sales:",np.sum(sales_data[:,3]/sales_data[:,3].size))
print("beauty total sales:",np.sum(sales_data[:,4]/sales_data[:,4].size))
print("sports total sales:",np.sum(sales_data[:,5]/sales_data[:,5].size))

 electronics total sales: 858000.0
groceries total sales: 437000.0
clothing  total sales: 320000.0
furniture total sales: 283000.0
beauty total sales: 202000.0
sports total sales: 235000.0


Question 16: Highest-Selling Store Identify:

Index of the store with the highest total sales Name of the store Total sales generated by that store Use np.argmax().

In [141]:
store_total_sales=np.sum(sales_data,axis=1)
highest_score_index=np.argmax(store_total_sales)
store_name=stores[highest_score_index]
total_sales=store_total_sales[highest_score_index]
print("index of the highest store:",highest_score_index)
print("store name:",store_name)
print("total sales:",total_sales)


index of the highest store: 3
store name: Mumbai
total sales: 2820000


Question 17: Lowest-Selling Store Identify the store with the lowest overall sales.

Use np.argmin().

In [147]:
store_total_sales=np.sum(sales_data,axis=1)
lowest_score_index=np.argmin(store_total_sales)
store_name=stores[lowest_score_index]
total_sales=store_total_sales[lowest_score_index]
print("index of the lowest store:",lowest_score_index)
print("store name:",store_name)
print("total sales:",total_sales)

index of the lowest store: 4
store name: Pune
total sales: 1980000


Question 18: Highest-Selling Category Find the product category that generated the highest total sales across the company.

In [148]:
category_total_sales=np.sum(sales_data,axis=0)
highest_category_index=np.argmax(category_total_sales)
category_name=categories[highest_category_index]
total_sales=category_total_sales[highest_score_index]
print("index of the highest store:",highest_category_index)
print("category name:",category_name)
print("total sales:",total_sales)

index of the highest store: 0
category name: Electronics
total sales: 1415000


Question 19: Lowest-Selling Category Find the product category with the lowest total sales across all stores.

In [166]:
category_total_sales=np.sum(sales_data,axis=0)
lowest_category_index=np.argmin(category_total_sales)
category_name=categories[lowest_score_index]
total_sales=store_total_sales[lowest_category_index]
print("index of the lowest store:",lowest_category_index)
print("category name:",category_name)
print("total sales:",total_sales)

index of the lowest store: 4
category name: Beauty
total sales: 1980000


Part 5: Cost Analysis
 Question 20: Total Company Cost Calculate the total cost incurred by SmartMart across all stores and product categories.

In [172]:
print("total cast of smartmart across stores and products:",np.sum(cost_data))

total cast of smartmart across stores and products: 8600000


Question 21: Store-Wise Cost Calculate the total cost incurred by each store.

In [181]:
print("bengaluru store:",np.sum(cost_data[0]))
print("bengaluru store:",np.sum(cost_data[1]))
print("bengaluru store:",np.sum(cost_data[2]))
print("bengaluru store:",np.sum(cost_data[3]))
print("bengaluru store:",np.sum(cost_data[4]))

bengaluru store: 1665000
bengaluru store: 1685000
bengaluru store: 1710000
bengaluru store: 2065000
bengaluru store: 1475000


Question 22: Category-Wise Cost Calculate the total cost incurred for each product category across all stores.

In [200]:
print("electronic category:",np.sum(cost_data[:,0]))
print("groceries category:",np.sum(cost_data[:,1]))
print("clothing category:",np.sum(cost_data[:,2]))
print("furniture category:",np.sum(cost_data[:,3]))
print("beauty category:",np.sum(cost_data[:,4]))
print("sports category:",np.sum(cost_data[:,5]))

electronic category: 3250000
groceries category: 1660000
clothing category: 1145000
furniture category: 1045000
beauty category: 665000
sports category: 835000


Question 23: Most Expensive Store Identify the store with the highest total operating cost.

In [204]:
highest_store=np.max(cost_data,axis=1)
highest_index=np.argmax(highest_store)
store_name=stores[highest_index]
print(store_name)

Mumbai


Question 24: Lowest-Cost Store Identify the store with the lowest total cost.

In [205]:
lowest_store=np.min(cost_data,axis=1)
lowest_store_index=np.argmin(lowest_store)
store_name=stores[lowest_score_index]
print(store_name)

Pune


Question 25: Most Expensive Product Category Determine which product category has the highest total cost across all stores

In [206]:
product_sum=np.sum(cost_data,axis=0)
highest_product=np.argmax(product_sum)
product_name=categories[highest_product]
print(product_name)

Electronics


Part 6: Profit Analysis Using Two Arrays Question 26: Profit Matrix Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data Display the complete profit matrix

In [207]:
profit=sales_data-cost_data
print(profit)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 27: Store-Wise Profit Calculate the total profit generated by each store.

In [208]:
profit=np.sum(sales_data,axis=1)-np.sum(cost_data,axis=1)
print(profit)

[605000 610000 600000 755000 505000]


Question 28: Category-Wise Profit Calculate the total profit generated by each product category.

In [209]:
profit_category=np.sum(sales_data,axis=0)-np.sum(cost_data,axis=0)
print(profit_category)

[1040000  525000  455000  370000  345000  340000]


Question 29: Most Profitable Store Identify the store that generated the highest total profit.

Display:

Store name Total sales Total cost Total profit

In [210]:
profit=np.sum(sales_data,axis=1) - np.sum(cost_data,axis=1)
profit_index=np.argmax(profit)
profit_store_name=stores[profit_index]
total_sales=np.sum(sales_data[profit_index])
total_cost=np.sum(cost_data[profit_index])
print(profit_store_name)
print(profit[profit_index])
print(total_sales)
print(total_cost)

Mumbai
755000
2820000
2065000


Question 30: Least Profitable Store Identify the store that generated the lowest total profit.

In [221]:
profit=np.sum(sales_data,axis=1) - np.sum(cost_data,axis=1)
profit_index=np.argmin(profit)
profit_store_name=stores[profit_index]
total_sales=np.sum(sales_data[profit_index])
total_cost=np.sum(cost_data[profit_index])
print(profit_store_name)
print(profit[profit_index])
print(total_sales)
print(total_cost)

Pune
505000
1980000
1475000


Question 31: Most Profitable Category Find the category with the highest total profit across all stores

In [222]:
profit=np.sum(sales_data,axis=0) - np.sum(cost_data,axis=0)
profit_index=np.argmax(profit)
category_name=categories[profit_index]
print(category_name)

Electronics


Question 32: Least Profitable Category Find the category with the lowest total profit.

In [235]:
profit=np.sum(sales_data,axis=0) - np.sum(cost_data,axis=0)
profit_index=np.argmin(profit)
category_name=categories[profit_index]
print(category_name)

Sports


Question 33: Maximum Individual Profit Find the highest profit generated by any single store-category combination.

Display:

Profit amount Store name Product category Use np.unravel_index().

In [246]:
profit=sales_data-cost_data
max_index=np.unravel_index(np.argmax(profit),profit.shape)
max_profit=profit[max_index]
store_name=stores[max_index[0]]
category_name=categories[max_index[1]]
print("maximum profit:",max_profit)
print("store name:",store_name)
print("category name:",category_name)

maximum profit: 260000
store name: Mumbai
category name: Electronics


Question 34: Minimum Individual Profit Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [258]:
profit=sales_data-cost_data
min_index=np.unravel_index(np.argmin(profit),profit.shape)
print(min_index)
store_name=stores[min_index[0]]
category_name=categories[min_index[1]]
min_profit=profit[min_index]
print("minimum profit:",min_profit)
print("store name:",store_name)
print("category name:",category_name)

(np.int64(4), np.int64(3))
minimum profit: 55000
store name: Pune
category name: Furniture


Part 7: Profit Margin Analysis Question 35: Profit Margin Matrix Calculate the profit margin percentage for every store-category combination.

Use:

profit_margin = (profit_data / sales_data) * 100 Round the result to two decimal places.

In [274]:
profit_data=sales_data-cost_data
profit_margin=(profit_data / sales_data) * 100
max_profit_margin_index=np.unravel_index(np.argmax(profit_margin),profit_margin.shape)
profit=profit_margin[max_profit_margin_index]
store_name=stores[max_profit_margin_index[0]]
category_name=categories[max_profit_margin_index[1]]
print(profit)
print(store_name)
print(category_name)

35.13513513513514
Chennai
Beauty


Question 36: Store-Wise Profit Margin Calculate the overall profit margin percentage for each store using:

Store Profit Margin = Total Store Profit / Total Store Sales × 100

In [275]:
profit_data=np.sum(sales_data,axis=1)-np.sum(cost_data,axis=1)
total_sales_data=np.sum(sales_data,axis=1)
profit_margin=(profit_data/total_sales_data)*100
print(np.round(profit_margin,2))

[26.65 26.58 25.97 26.77 25.51]


Question 37: Category-Wise Profit Margin Calculate the overall profit margin percentage for each product category.

In [302]:
profit=np.sum(sales_data,axis=0)-np.sum(cost_data,axis=0)
total_sales_data=np.sum(sales_data,axis=0)
profit_margin=(profit/total_sales_data)*100
print(np.round(profit_margin,2))

[24.24 24.03 28.44 26.15 34.16 28.94]


Question 38: Best Store by Profit Margin Identify the store with the highest overall profit margin.

In [315]:
profit=np.sum(sales_data,axis=1)-np.sum(cost_data,axis=1)
total_sales_data=np.sum(sales_data,axis=1)
profit_margin=(profit/total_sales_data)*100
store_index=np.argmax(profit_margin)
store_name=stores[store_index]
print(store_name)
print("highest profit margin:",np.round(profit_margin[store_index],2))

Mumbai
highest profit margin: 26.77


Question 39: Best Category by Profit Margin Identify the product category with the highest profit margin.

In [333]:
profit=np.sum(sales_data,axis=0)-np.sum(cost_data,axis=0)
total_sales_data=np.sum(sales_data,axis=0)
profit_margin=(profit/total_sales_data)*100
category_index=np.argmax(profit_margin)
category_name=categories[category_index]
print(category_name)
print("highest profit margin:",np.round(profit_margin[category_index],2))

Beauty
highest profit margin: 34.16


Question 40: Low-Margin Transactions Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store Category Sales Cost Profit Profit margin Use Boolean indexing.

In [334]:
profit_margin.shape

(6,)

In [335]:
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
below_margin=profit_margin < 22
print(below_margin)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


Part 8: Boolean Filtering Question 41: High Sales Values Find all sales values greater than ₹5,00,000.

In [351]:
sales_values=sales_data > 500000
sales_index=np.where(sales_values)
print(sales_index)
print(sales_data[sales_index])

(array([0, 1, 2, 3, 3, 4]), array([0, 0, 0, 0, 1, 0]))
[ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values Find all sales values below ₹2,00,000.

In [352]:
sales_values=sales_data < 200000
sales_index=np.where(sales_values)
print(sales_index)
print(sales_data[sales_index])

(array([0, 2, 4]), array([4, 4, 4]))
[190000 185000 175000]


Question 43: High Profit Values Find all store-category combinations where profit is greater than ₹1,50,000.

In [384]:
profit=sales_data-cost_data
profit_data=profit > 150000
store_index=np.where(profit_data)
print(profit[store_index])

[210000 190000 220000 260000 160000]


Question 44: Moderate Sales Range Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [394]:
sales_value=(sales_data >250000) & (sales_data<500000)
print(sales_data[sales_value])

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 290000 405000 280000]


Question 45: Premium Performance A store-category combination is considered premium when:

Sales are greater than ₹5,00,000 Profit is greater than ₹1,50,000 Find all premium-performing combinations.

In [395]:
profit=sales_data - cost_data
premium=np.logical_and(sales_data > 500000,profit > 150000)
store_index,category_index=np.where(premium)
print(sales_data[store_index,category_index])
print(profit[store_index,category_index])

[ 850000  780000  920000 1050000  690000]
[210000 190000 220000 260000 160000]


Question 46: Underperforming Combinations A store-category combination is considered underperforming when:

Sales are below ₹2,50,000 Profit margin is below 25% Find all such combinations.

In [407]:
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
underperforming=np.logical_and(sales_data < 250000,profit_margin < 25)
store_index,category_index=np.where(underperforming)
for i,j in zip(store_index,category_index):
  print("store:",stores[i])
  print("category:",categories[j])
  print("profit:",profit[i,j])
  print("sales:",sales_data[i,j])
  print("profit_margin:",profit_margin[i,j])

store: Pune
category: Furniture
profit: 55000
sales: 225000
profit_margin: 24.444444444444443


Question 47: Category Performance Classification Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000 "Medium" when sales are between ₹2,50,000 and ₹4,99,999 "Low" when sales are below ₹2,50,000 Use np.where() or np.select().

In [412]:
classification=np.where(
    sales_data >= 500000,
    "high",np.where((sales_data >= 250000) & (sales_data <499999),"medium","low"))

print(classification)

[['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'high' 'medium' 'medium' 'medium' 'medium']
 ['high' 'medium' 'medium' 'low' 'low' 'low']]


Question 48: Target Comparison Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [444]:
sales_targets = np.array([800000, 400000, 300000, 280000, 200000, 230000])
result = sales_data >= sales_targets
print(result)

TypeError: 'numpy.ndarray' object is not callable