In [4]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)


Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

Question 1: Array Dimensions The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data Shape of sales_data Total number of values Data type of the array Memory occupied by the array


In [30]:
import numpy as np
print("no of dimensions:",sales_data.ndim)
print("shape of sales data:",sales_data.shape)
print("total no of values:",sales_data.size)
print("data type of the array:",sales_data.dtype)
print("memory occupied:",sales_data.nbytes,"bytes")

no of dimensions: 2
shape of sales data: (5, 6)
total no of values: 30
data type of the array: int64
memory occupied: 240 bytes


Question 2: Store and Category Count Calculate the following:

Total number of stores Total number of product categories Total number of store-category combinations

In [41]:
import numpy as np
print("total no of stores:",stores.size)
print("total no of product categories:",categories.size)
print("total no of store-category combinations:",stores.size*categories.size)

total no of stores: 5
total no of product categories: 6
total no of store-category combinations: 30


Question 3: Sales Data Type Conversion The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32 float64 Compare the memory used by both arrays.

In [48]:
sales_float32=sales_data.astype(np.float32)
sales_float64=sales_data.astype(np.float64)
print("memory used sales data float32:",sales_float64.nbytes,"bytes")
print("memory used sales_data float64:",sales_float32.nbytes,"nbytes")
print("sales data float32:",sales_float32.dtype)
print("sales_data float64:",sales_float64.dtype)

memory used sales data float32: 240 bytes
memory used sales_data float64: 120 nbytes
sales data float32: float32
sales_data float64: float64


Part 3: Indexing and Data Extraction

Question 4: Bengaluru Store Analysis The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [49]:
print("sales for bengaluru:",sales_data[0])

sales for bengaluru: [850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis Extract the total cost incurred by the Mumbai store for all product categories.

In [50]:
print(np.sum(sales_data[3]))

2820000


Question 6: Electronics Sales Across Stores The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [51]:
print(sales_data[:,0])

[ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores Extract the Clothing cost for every store from cost_data

In [52]:
print(cost_data[:,2])

[220000 210000 245000 265000 205000]


Question 8: Hyderabad Furniture Performance Find the following for Hyderabad:

Furniture sales Furniture cost Furniture profit

In [53]:
print("furniture sales:",sales_data[1,3])
print("furniture cost:",cost_data[1,3])
print("profit:",sales_data[1,3]-cost_data[1,3])

furniture sales: 310000
furniture cost: 225000
profit: 85000


Question 9: Chennai Category Range Extract Chennai’s sales for the following categories:

Groceries Clothing Furniture Use array slicing.

In [54]:
print("chennai sales on groceries:",sales_data[2,1],)
print("clothing:",sales_data[2,2])
print("furnitute:",sales_data[2,3])

chennai sales on groceries: 390000
clothing: 340000
furnitute: 260000


Question 10: Selected Store Analysis Extract sales data for:

Bengaluru Chennai Pune Include only:

Electronics Clothing Beauty Use advanced indexing.

In [55]:
print("bengaluru sales on electronics:",sales_data[0,0])
print("bengaluru sales on clothing:",sales_data[0,2])
print("bengaluru sales on beauty:",sales_data[0,4])
print("chennai sales on electronics:",sales_data[2,0])
print("chennai sales on clothing:",sales_data[2,2])
print("chennai sales on beauty:",sales_data[2,4])
print("pune sales on electronics:",sales_data[4,0])
print("pune sales on clothing:",sales_data[4,2])
print("pune sales on beauty:",sales_data[4,4])


bengaluru sales on electronics: 850000
bengaluru sales on clothing: 310000
bengaluru sales on beauty: 190000
chennai sales on electronics: 920000
chennai sales on clothing: 340000
chennai sales on beauty: 185000
pune sales on electronics: 690000
pune sales on clothing: 280000
pune sales on beauty: 175000


Part 4: Sales Aggregation

Question 11: Company-Wide Sales Calculate the total sales revenue generated by all stores and all categories.

In [69]:
print(np.sum(sales_data))

11675000


Question 12: Store-Wise Sales Calculate total sales revenue for each store.

Display the result together with the store names.

In [81]:
print("bengaluru total sales:",np.sum(sales_data[0]))
print("hyderabad total sales:",np.sum(sales_data[1]))
print("chennai total sales:",np.sum(sales_data[2]))
print("mumbai total sales:",np.sum(sales_data[3]))
print("pune total sales:",np.sum(sales_data[4]))

bengaluru total sales: 2270000
hyderabad total sales: 2295000
chennai total sales: 2310000
mumbai total sales: 2820000
pune total sales: 1980000


Question 13: Category-Wise Sales Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [86]:
print(" electronics total sales:",np.sum(sales_data[:,0]))
print("groceries total sales:",np.sum(sales_data[:,1]))
print("clothing  total sales:",np.sum(sales_data[:,2]))
print("furniture total sales:",np.sum(sales_data[:,3]))
print("beauty total sales:",np.sum(sales_data[:,4]))
print("sports total sales:",np.sum(sales_data[:,5]))

 electronics total sales: 4290000
groceries total sales: 2185000
clothing  total sales: 1600000
furniture total sales: 1415000
beauty total sales: 1010000
sports total sales: 1175000


Question 14: Average Sales Per Store Calculate the average sales generated by each store across all six product categories.

In [100]:
print(sum(sales_data[0]/sales_data[0].size))
print(sum(sales_data[1]/sales_data[1].size))
print(sum(sales_data[2]/sales_data[2].size))
print(sum(sales_data[3]/sales_data[3].size))
print(sum(sales_data[4]/sales_data[4].size))

378333.3333333333
382500.0
384999.99999999994
470000.0
330000.0


Question 15: Average Sales Per Category Calculate the average sales of each product category across the five stores

In [123]:
print(" electronics total sales:",np.sum(sales_data[:,0]/sales_data[:,0].size))
print("groceries total sales:",np.sum(sales_data[:,1]/sales_data[:,1].size))
print("clothing  total sales:",np.sum(sales_data[:,2]/sales_data[:,2].size))
print("furniture total sales:",np.sum(sales_data[:,3]/sales_data[:,3].size))
print("beauty total sales:",np.sum(sales_data[:,4]/sales_data[:,4].size))
print("sports total sales:",np.sum(sales_data[:,5]/sales_data[:,5].size))

 electronics total sales: 858000.0
groceries total sales: 437000.0
clothing  total sales: 320000.0
furniture total sales: 283000.0
beauty total sales: 202000.0
sports total sales: 235000.0


Question 16: Highest-Selling Store Identify:

Index of the store with the highest total sales Name of the store Total sales generated by that store Use np.argmax().

In [141]:
store_total_sales=np.sum(sales_data,axis=1)
highest_score_index=np.argmax(store_total_sales)
store_name=stores[highest_score_index]
total_sales=store_total_sales[highest_score_index]
print("index of the highest store:",highest_score_index)
print("store name:",store_name)
print("total sales:",total_sales)


index of the highest store: 3
store name: Mumbai
total sales: 2820000


Question 17: Lowest-Selling Store Identify the store with the lowest overall sales.

Use np.argmin().

In [147]:
store_total_sales=np.sum(sales_data,axis=1)
lowest_score_index=np.argmin(store_total_sales)
store_name=stores[lowest_score_index]
total_sales=store_total_sales[lowest_score_index]
print("index of the lowest store:",lowest_score_index)
print("store name:",store_name)
print("total sales:",total_sales)

index of the lowest store: 4
store name: Pune
total sales: 1980000


Question 18: Highest-Selling Category Find the product category that generated the highest total sales across the company.

In [148]:
category_total_sales=np.sum(sales_data,axis=0)
highest_category_index=np.argmax(category_total_sales)
category_name=categories[highest_category_index]
total_sales=category_total_sales[highest_score_index]
print("index of the highest store:",highest_category_index)
print("category name:",category_name)
print("total sales:",total_sales)

index of the highest store: 0
category name: Electronics
total sales: 1415000


Question 19: Lowest-Selling Category Find the product category with the lowest total sales across all stores.

In [166]:
category_total_sales=np.sum(sales_data,axis=0)
lowest_category_index=np.argmin(category_total_sales)
category_name=categories[lowest_score_index]
total_sales=store_total_sales[lowest_category_index]
print("index of the lowest store:",lowest_category_index)
print("category name:",category_name)
print("total sales:",total_sales)

index of the lowest store: 4
category name: Beauty
total sales: 1980000


Part 5: Cost Analysis
 Question 20: Total Company Cost Calculate the total cost incurred by SmartMart across all stores and product categories.

In [172]:
print("total cast of smartmart across stores and products:",np.sum(cost_data))

total cast of smartmart across stores and products: 8600000


Question 21: Store-Wise Cost Calculate the total cost incurred by each store.

In [181]:
print("bengaluru store:",np.sum(cost_data[0]))
print("bengaluru store:",np.sum(cost_data[1]))
print("bengaluru store:",np.sum(cost_data[2]))
print("bengaluru store:",np.sum(cost_data[3]))
print("bengaluru store:",np.sum(cost_data[4]))

bengaluru store: 1665000
bengaluru store: 1685000
bengaluru store: 1710000
bengaluru store: 2065000
bengaluru store: 1475000


Question 22: Category-Wise Cost Calculate the total cost incurred for each product category across all stores.

In [200]:
print("electronic category:",np.sum(cost_data[:,0]))
print("groceries category:",np.sum(cost_data[:,1]))
print("clothing category:",np.sum(cost_data[:,2]))
print("furniture category:",np.sum(cost_data[:,3]))
print("beauty category:",np.sum(cost_data[:,4]))
print("sports category:",np.sum(cost_data[:,5]))

electronic category: 3250000
groceries category: 1660000
clothing category: 1145000
furniture category: 1045000
beauty category: 665000
sports category: 835000


Question 23: Most Expensive Store Identify the store with the highest total operating cost.

In [204]:
highest_store=np.max(cost_data,axis=1)
highest_index=np.argmax(highest_store)
store_name=stores[highest_index]
print(store_name)

Mumbai


Question 24: Lowest-Cost Store Identify the store with the lowest total cost.

In [205]:
lowest_store=np.min(cost_data,axis=1)
lowest_store_index=np.argmin(lowest_store)
store_name=stores[lowest_score_index]
print(store_name)

Pune


Question 25: Most Expensive Product Category Determine which product category has the highest total cost across all stores

In [206]:
product_sum=np.sum(cost_data,axis=0)
highest_product=np.argmax(product_sum)
product_name=categories[highest_product]
print(product_name)

Electronics


Part 6: Profit Analysis Using Two Arrays Question 26: Profit Matrix Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data Display the complete profit matrix

In [207]:
profit=sales_data-cost_data
print(profit)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 27: Store-Wise Profit Calculate the total profit generated by each store.

In [208]:
profit=np.sum(sales_data,axis=1)-np.sum(cost_data,axis=1)
print(profit)

[605000 610000 600000 755000 505000]


Question 28: Category-Wise Profit Calculate the total profit generated by each product category.

In [209]:
profit_category=np.sum(sales_data,axis=0)-np.sum(cost_data,axis=0)
print(profit_category)

[1040000  525000  455000  370000  345000  340000]


Question 29: Most Profitable Store Identify the store that generated the highest total profit.

Display:

Store name Total sales Total cost Total profit

In [210]:
profit=np.sum(sales_data,axis=1) - np.sum(cost_data,axis=1)
profit_index=np.argmax(profit)
profit_store_name=stores[profit_index]
total_sales=np.sum(sales_data[profit_index])
total_cost=np.sum(cost_data[profit_index])
print(profit_store_name)
print(profit[profit_index])
print(total_sales)
print(total_cost)

Mumbai
755000
2820000
2065000


Question 30: Least Profitable Store Identify the store that generated the lowest total profit.

In [221]:
profit=np.sum(sales_data,axis=1) - np.sum(cost_data,axis=1)
profit_index=np.argmin(profit)
profit_store_name=stores[profit_index]
total_sales=np.sum(sales_data[profit_index])
total_cost=np.sum(cost_data[profit_index])
print(profit_store_name)
print(profit[profit_index])
print(total_sales)
print(total_cost)

Pune
505000
1980000
1475000


Question 31: Most Profitable Category Find the category with the highest total profit across all stores

In [222]:
profit=np.sum(sales_data,axis=0) - np.sum(cost_data,axis=0)
profit_index=np.argmax(profit)
category_name=categories[profit_index]
print(category_name)

Electronics


Question 32: Least Profitable Category Find the category with the lowest total profit.

In [235]:
profit=np.sum(sales_data,axis=0) - np.sum(cost_data,axis=0)
profit_index=np.argmin(profit)
category_name=categories[profit_index]
print(category_name)

Sports


Question 33: Maximum Individual Profit Find the highest profit generated by any single store-category combination.

Display:

Profit amount Store name Product category Use np.unravel_index().

In [246]:
profit=sales_data-cost_data
max_index=np.unravel_index(np.argmax(profit),profit.shape)
max_profit=profit[max_index]
store_name=stores[max_index[0]]
category_name=categories[max_index[1]]
print("maximum profit:",max_profit)
print("store name:",store_name)
print("category name:",category_name)

maximum profit: 260000
store name: Mumbai
category name: Electronics


Question 34: Minimum Individual Profit Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [258]:
profit=sales_data-cost_data
min_index=np.unravel_index(np.argmin(profit),profit.shape)
print(min_index)
store_name=stores[min_index[0]]
category_name=categories[min_index[1]]
min_profit=profit[min_index]
print("minimum profit:",min_profit)
print("store name:",store_name)
print("category name:",category_name)

(np.int64(4), np.int64(3))
minimum profit: 55000
store name: Pune
category name: Furniture


Part 7: Profit Margin Analysis Question 35: Profit Margin Matrix Calculate the profit margin percentage for every store-category combination.

Use:

profit_margin = (profit_data / sales_data) * 100 Round the result to two decimal places.

In [274]:
profit_data=sales_data-cost_data
profit_margin=(profit_data / sales_data) * 100
max_profit_margin_index=np.unravel_index(np.argmax(profit_margin),profit_margin.shape)
profit=profit_margin[max_profit_margin_index]
store_name=stores[max_profit_margin_index[0]]
category_name=categories[max_profit_margin_index[1]]
print(profit)
print(store_name)
print(category_name)

35.13513513513514
Chennai
Beauty


Question 36: Store-Wise Profit Margin Calculate the overall profit margin percentage for each store using:

Store Profit Margin = Total Store Profit / Total Store Sales × 100

In [275]:
profit_data=np.sum(sales_data,axis=1)-np.sum(cost_data,axis=1)
total_sales_data=np.sum(sales_data,axis=1)
profit_margin=(profit_data/total_sales_data)*100
print(np.round(profit_margin,2))

[26.65 26.58 25.97 26.77 25.51]


Question 37: Category-Wise Profit Margin Calculate the overall profit margin percentage for each product category.

In [302]:
profit=np.sum(sales_data,axis=0)-np.sum(cost_data,axis=0)
total_sales_data=np.sum(sales_data,axis=0)
profit_margin=(profit/total_sales_data)*100
print(np.round(profit_margin,2))

[24.24 24.03 28.44 26.15 34.16 28.94]


Question 38: Best Store by Profit Margin Identify the store with the highest overall profit margin.

In [315]:
profit=np.sum(sales_data,axis=1)-np.sum(cost_data,axis=1)
total_sales_data=np.sum(sales_data,axis=1)
profit_margin=(profit/total_sales_data)*100
store_index=np.argmax(profit_margin)
store_name=stores[store_index]
print(store_name)
print("highest profit margin:",np.round(profit_margin[store_index],2))

Mumbai
highest profit margin: 26.77


Question 39: Best Category by Profit Margin Identify the product category with the highest profit margin.

In [333]:
profit=np.sum(sales_data,axis=0)-np.sum(cost_data,axis=0)
total_sales_data=np.sum(sales_data,axis=0)
profit_margin=(profit/total_sales_data)*100
category_index=np.argmax(profit_margin)
category_name=categories[category_index]
print(category_name)
print("highest profit margin:",np.round(profit_margin[category_index],2))

Beauty
highest profit margin: 34.16


Question 40: Low-Margin Transactions Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store Category Sales Cost Profit Profit margin Use Boolean indexing.

In [334]:
profit_margin.shape

(6,)

In [335]:
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
below_margin=profit_margin < 22
print(below_margin)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


Part 8: Boolean Filtering Question 41: High Sales Values Find all sales values greater than ₹5,00,000.

In [351]:
sales_values=sales_data > 500000
sales_index=np.where(sales_values)
print(sales_index)
print(sales_data[sales_index])

(array([0, 1, 2, 3, 3, 4]), array([0, 0, 0, 0, 1, 0]))
[ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values Find all sales values below ₹2,00,000.

In [352]:
sales_values=sales_data < 200000
sales_index=np.where(sales_values)
print(sales_index)
print(sales_data[sales_index])

(array([0, 2, 4]), array([4, 4, 4]))
[190000 185000 175000]


Question 43: High Profit Values Find all store-category combinations where profit is greater than ₹1,50,000.

In [384]:
profit=sales_data-cost_data
profit_data=profit > 150000
store_index=np.where(profit_data)
print(profit[store_index])

[210000 190000 220000 260000 160000]


Question 44: Moderate Sales Range Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [394]:
sales_value=(sales_data >250000) & (sales_data<500000)
print(sales_data[sales_value])

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 290000 405000 280000]


Question 45: Premium Performance A store-category combination is considered premium when:

Sales are greater than ₹5,00,000 Profit is greater than ₹1,50,000 Find all premium-performing combinations.

In [395]:
profit=sales_data - cost_data
premium=np.logical_and(sales_data > 500000,profit > 150000)
store_index,category_index=np.where(premium)
print(sales_data[store_index,category_index])
print(profit[store_index,category_index])

[ 850000  780000  920000 1050000  690000]
[210000 190000 220000 260000 160000]


Question 46: Underperforming Combinations A store-category combination is considered underperforming when:

Sales are below ₹2,50,000 Profit margin is below 25% Find all such combinations.

In [407]:
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
underperforming=np.logical_and(sales_data < 250000,profit_margin < 25)
store_index,category_index=np.where(underperforming)
for i,j in zip(store_index,category_index):
  print("store:",stores[i])
  print("category:",categories[j])
  print("profit:",profit[i,j])
  print("sales:",sales_data[i,j])
  print("profit_margin:",profit_margin[i,j])

store: Pune
category: Furniture
profit: 55000
sales: 225000
profit_margin: 24.444444444444443


Question 47: Category Performance Classification Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000 "Medium" when sales are between ₹2,50,000 and ₹4,99,999 "Low" when sales are below ₹2,50,000 Use np.where() or np.select().

In [412]:
classification=np.where(
    sales_data >= 500000,
    "high",np.where((sales_data >= 250000) & (sales_data <499999),"medium","low"))

print(classification)

[['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'high' 'medium' 'medium' 'medium' 'medium']
 ['high' 'medium' 'medium' 'low' 'low' 'low']]


Question 48: Target Comparison Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [18]:
sales_data = np.array([
[850000, 420000, 310000, 275000, 190000, 225000],
[780000, 460000, 295000, 310000, 210000, 240000],
[920000, 390000, 340000, 260000, 185000, 215000],
[1050000, 510000, 375000, 345000, 250000, 290000],
[690000, 405000, 280000, 225000, 175000, 205000]
])

In [21]:
import numpy as np
sales_targets = np.array([800000, 400000, 300000, 280000, 200000, 230000])
result = sales_data >= sales_targets
print(result)

[[ True  True  True False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False  True False False False False]]


Question 49: Target Achievement Matrix Create a Boolean array where:

True means the store achieved the category target False means the store failed to achieve the target

In [24]:
target_reached=np.where(sales_data>sales_targets,True,False)
print(target_reached)

[[ True  True  True False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False  True False False False False]]


Question 50: Target Achievement Count Calculate the number of categories in which each store achieved its target.

In [27]:
import numpy as np

stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])
sales_targets = np.array([800000, 400000, 300000, 280000, 200000, 230000])
target_achieved = sales_data >= sales_targets
achievement_count = np.sum(target_achieved, axis=1)
for store, count in zip(stores, achievement_count):
    print(store, ":", count)

Bengaluru : 3
Hyderabad : 4
Chennai : 2
Mumbai : 6
Pune : 1


Question 51: Best Target-Performing Store Find the store that achieved the highest number of category targets.

In [32]:
target=np.sum(sales_data>=sales_targets,axis=1)
target_index=np.argmax(target)
store_name=stores[target_index]
print(store_name)
print(target[target_index])

Mumbai
6


Question 52: Target Achievement by Category Calculate how many stores achieved the target for each product category.

In [34]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)


Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


In [35]:
target=np.sum(sales_data>=sales_targets,axis=0)
for category,count in zip(categories,target):
  print(category,":",count)

Electronics : 3
Groceries : 4
Clothing : 3
Furniture : 2
Beauty : 2
Sports : 2


Question 53: Sales Target Variance Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

In [ ]:
variance = sales_data - sales_targets
for i in variance:
    print(i)

[ 50000  20000  10000  -5000 -10000  -5000]
[-20000  60000  -5000  30000  10000  10000]
[120000 -10000  40000 -20000 -15000 -15000]
[250000 110000  75000  65000  50000  60000]
[-110000    5000  -20000  -55000  -25000  -25000]


Question 54: Percentage Above or Below Target Calculate the percentage variance from the target using:

Percentage Variance = (Actual Sales - Target Sales) / Target Sales × 100

In [37]:
percentage_variance=(sales_data-sales_targets)/(sales_targets)*100
for i in percentage_variance:
  print(i)

[ 6.25        5.          3.33333333 -1.78571429 -5.         -2.17391304]
[-2.5        15.         -1.66666667 10.71428571  5.          4.34782609]
[15.         -2.5        13.33333333 -7.14285714 -7.5        -6.52173913]
[31.25       27.5        25.         23.21428571 25.         26.08695652]
[-13.75         1.25        -6.66666667 -19.64285714 -12.5
 -10.86956522]


Question 55: Stores Missing Electronics Target Identify stores that failed to achieve the Electronics sales target.

Hyderabad
Pune
Question 56: Stores Achieving All Targets Check whether any store achieved its target in all six product categories.

Use np.all().

In [38]:
store_target=np.all(sales_data >= sales_targets,axis=1)
for i,j in zip(stores,store_target):
  if  j:
    print(i)

Mumbai


Question 57: Stores Achieving At Least One Target Identify stores that achieved at least one category target.

Use np.any().

In [39]:
store_target=np.any(sales_data >= sales_targets,axis=1)
for i,j in zip(stores,store_target):
  if  j:
    print(i)

Bengaluru
Hyderabad
Chennai
Mumbai
Pune


Question 58: Discount Amount Matrix Calculate the discount amount for each store-category combination.

Use broadcasting.

In [48]:
import numpy as np
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [51]:
discount_amount = sales_data * discount_rates
print(np.round(discount_amount,2))

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


Question 59: Sales After Discount Calculate the net sales value after applying the category-wise discounts.

In [57]:
discount_amount = sales_data * discount_rates
net_sales_value=sales_data-discount_amount
print(net_sales_value)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


Question 60: Profit After Discount Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [68]:
discount_amount = sales_data * discount_rates
net_sales_value=sales_data-discount_amount
new_profit=net_sales_value-cost_data
print(new_profit)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount Calculate the new profit margin after applying discounts.

In [69]:
discount_amount = sales_data * discount_rates
net_sales_value = sales_data - discount_amount
new_profit = net_sales_value - cost_data
new_margin = (new_profit / net_sales_value) * 100
print(np.round(new_margin, 2))

[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


Question 62: Loss-Making Transactions Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [ ]:
discounted_sales = sales_data * (1 - discount_rates)
loss = discounted_sales < cost_data
if not np.any(loss):
    print("No loss-making transactions")
else:
    for i in range(len(stores)):
        for j in range(len(categories)):
            if loss[i, j]:
                print(stores[i], "-", categories[j])

No loss-making transactions


Question 63: Discount Impact Calculate how much total revenue the company loses because of the proposed discounts.

In [83]:
discount_amount=sales_data*discount_rates
total_revenue_lost = np.sum(discount_amount)
print(f"Total revenue lost due to discounts: {total_revenue_lost:.2f}")

Total revenue lost due to discounts: 1146350.00


Question 64: Store Most Affected by Discounts Identify the store that loses the highest amount of revenue due to discounts.

In [88]:
discount=np.sum(sales_data*discount_rates,axis=1)
max_discount=np.argmax(discount)
store_name=stores[max_discount]
print(store_name)
print(discount[max_discount])

Mumbai
277150.0


Part 11: Tax and Price Adjustment The government introduces category-wise tax rates:

tax_rates = np.array([ 0.18, 0.05, 0.12, 0.18, 0.18, 0.12 ]) Question 65: Tax Collection Matrix Calculate the tax collected on sales for each store and category.

In [89]:
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

Question 65: Tax Collection Matrix Calculate the tax collected on sales for each store and category.

In [93]:
tax=sales_data*tax_rates
print(tax)  

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 66: Sales Including Tax Calculate the final customer billing value after adding tax.

In [94]:
tax=sales_data*discount_rates
print(cost_data+tax)

[[725000. 336000. 266500. 238000. 140200. 182500.]
 [668000. 373000. 254250. 262200. 156800. 194000.]
 [792000. 314500. 296000. 226200. 134800. 176500.]
 [895000. 415500. 321250. 291400. 185000. 234000.]
 [599000. 330250. 247000. 197000. 129000. 165500.]]


Question 67: Store-Wise Tax Collection Calculate the total tax collected by each store

In [95]:
tax_store=np.sum(sales_data*tax_rates,axis=1)
print(tax_store)

[321900. 321200. 331800. 401400. 274650.]


Question 68: Category-Wise Tax Collection Calculate total tax collected for each category.

In [96]:
tax=np.sum(sales_data*tax_rates,axis=0)
print(tax)

[772200. 109250. 192000. 254700. 181800. 141000.]


Question 69: Highest Tax-Contributing Store Identify the store that contributes the highest tax amount.

In [97]:
tax=np.sum(sales_data*tax_rates,axis=1)
max_tax_store=np.argmax(tax)
print(max_tax_store)
print(stores[max_tax_store])

3
Mumbai


Part 12: Array Modification

Question 70: Updated Pune Electronics Sales The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [98]:
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
new_sales=sales_data.copy()
new_sales[stores=="Pune",categories=="Electronics"]=740000
print(new_sales)
     

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


Question 71: Revised Beauty Cost Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [ ]:
new_cost_data=cost_data.copy()
cost_per=cost_data*0.08
new_cost=cost_data-cost_per
new_cost_data[:,categories=="Beauty"]=new_cost[:,categories=="Beauty"]
print(cost_data)
print(new_cost_data)   

[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]
[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


Question 72: Furniture Cost Increase Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [104]:
new_cost_data=cost_data.copy()
cost_per=cost_data*1.12
new_cost=cost_data+cost_per
new_cost_data[:,categories=="Furniture"]=new_cost[:,categories=="Furniture"]
print(new_cost_data)

[[640000 315000 220000 434600 125000 160000]
 [590000 350000 210000 477000 140000 170000]
 [700000 295000 245000 413400 120000 155000]
 [790000 390000 265000 530000 165000 205000]
 [530000 310000 205000 360400 115000 145000]]


Question 73: Store Closure Simulation Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [105]:
new_sales=sales_data.copy()
new_costs=cost_data.copy()
new_value1=np.delete(new_sales,np.where(stores=="Pune"),axis=0)
new_value2=np.delete(new_costs,np.where(stores=="Pune"),axis=0)
print(new_value1)
print(new_value2)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


Question 74: Adding a New Store A new Delhi store is opened with the following data:

delhi_sales = np.array([ 880000, 475000, 330000, 290000, 215000, 250000 ])

delhi_cost = np.array([ 665000, 360000, 235000, 215000, 145000, 180000 ])

In [106]:
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [107]:
import numpy as np
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
new_sales_data=np.vstack((sales_data,delhi_sales))
new_cost_data=np.vstack((cost_data,delhi_cost))
print(new_sales_data)
print(new_cost_data)
new_store=np.append(stores,"Delhi")
print(new_store)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


Question 75: Adding a New Product Category SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([ 360000, 325000, 390000, 420000, 295000 ])

home_appliance_cost = np.array([ 265000, 240000, 285000, 305000, 225000 ]) Add the new category as a column using np.column_stack() or np.hstack().

In [108]:
import numpy as np
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
new_sales=np.column_stack((sales_data,home_appliance_sales))
new_cost=np.column_stack((cost_data,home_appliance_cost))
print(new_sales)
print(new_cost)
new_category=np.append(categories,"Homeappliances")
print(new_category)

[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Homeappliances']


Part 13: Sorting and Ranking Question 76: Sort Stores by Sales Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [115]:
total_sales_data=np.sum(sales_data,axis=1)
sorting_order=np.argsort(total_sales_data)
for index in sorting_order:
  print(stores[index],":",total_sales_data[index])

Pune : 1980000
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000


Question 77: Rank Stores by Profit Rank stores from highest to lowest total profit.

Use np.argsort().

In [120]:
profit=np.sum(sales_data-cost_data,axis=1)
sorting_profit=np.argsort(-profit)
for index in sorting_profit:
  print(stores[index],":",profit[index])


Mumbai : 755000
Hyderabad : 610000
Bengaluru : 605000
Chennai : 600000
Pune : 505000


Question 78: Sort Categories by Revenue Sort product categories from highest to lowest total revenue.

In [ ]:
revenue=np.sum(sales_data,axis=0)
sorting=np.argsort(-revenue)
for index in sorting:
  print(categories[index],":",revenue[index])

Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Sports : 1175000
Beauty : 1010000


Question 79: Top Three Store-Category Sales Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value Store name Category name

In [122]:
new_sales=sales_data.flatten()
sorting=np.argsort(-new_sales)[0:3]
print(sorting)
for index in sorting:
  row,col=np.unravel_index(index,sales_data.shape)
  print(stores[row],":",categories[col],":",sales_data[row,col])

[18 12  0]
Mumbai : Electronics : 1050000
Chennai : Electronics : 920000
Bengaluru : Electronics : 850000


Question 80: Bottom Three Profits Find the three lowest profit values in the profit matrix.

In [131]:
profit=sales_data-cost_data
flattening=profit.flatten()
sorting=np.argsort(flattening)[0:3]
for index in sorting:
  row,col=np.unravel_index(index,profit.shape)
  print(stores[row],categories[col],profit[row,col])

Pune Furniture 55000
Pune Sports 60000
Chennai Sports 60000


Part 14: Statistical Analysis Question 81: Sales Statistics Calculate the following for the complete sales array:

Minimum Maximum Mean Median Standard deviation Variance 25th percentile 50th percentile 75th percentile

In [132]:
print(np.min(sales_data))
print(np.max(sales_data))
print(np.mean(sales_data))
print(np.median(sales_data))
print(np.std(sales_data))
print(np.var(sales_data))
print(np.percentile(sales_data,25))
print(np.percentile(sales_data,50))
print(np.percentile(sales_data,75))

175000
1050000
389166.6666666667
302500.0
230322.53954448793
53048472222.222206
228750.0
302500.0
416250.0


Question 82: Store-Wise Standard Deviation Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [133]:
standard_deviation=np.std(sales_data,axis=1)
max_store=np.argmax(standard_deviation)
store_name=stores[max_store]
print(store_name)
print(standard_deviation[max_store])

Mumbai
271860.871280391


Question 83: Category-Wise Standard Deviation Determine which product category has the highest variation in sales across stores.

In [134]:
standard_deviation=np.std(sales_data,axis=0)
max_store=np.argmax(standard_deviation)
print(categories[max_store],":",standard_deviation[max_store])

Electronics : 122539.78945632312


Question 84: Sales Above Company Average Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [140]:
average_sales=np.mean(sales_data)
max_val=sales_data > average_sales
counting_max_val=np.sum(max_val)
print(counting_max_val)

10


Question 85: Outlier Detection Treat any sales value greater than:

Mean + 1.5 × Standard Deviation as a high-value outlier.

Identify all such sales values.

In [142]:
mean_val=np.mean(sales_data)
std_val=np.std(sales_data)
outlier_val=mean_val+1.5*std_val
counting_outlier=np.where(sales_data > outlier_val)
sales_val=sales_data[counting_outlier]
print(sales_val)

[ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation

Question 86: Flatten Sales Data Convert the two-dimensional sales array into a one-dimensional array using:

flatten() ravel() Explain the difference between the two methods.

In [143]:
usage_flatten=sales_data.flatten()
usage_ravel=sales_data.ravel()
print(sales_data)
print(usage_flatten)
print(usage_ravel)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


Question 87: Reshape Sales Data Reshape the 5 × 6 sales array into:

3 × 10 10 × 3 2 × 15 15 × 2 Verify that no data is lost.

In [144]:
print(sales_data)
sales1=sales_data.reshape(3,10)
sales2=sales_data.reshape(10,3)
sales3=sales_data.reshape(2,15)
sales4=sales_data.reshape(15,2)
print(sales1)
print(sales2)
print(sales3)
print(sales4)
print(sales_data.size)
print(sales1.size)
print(sales2.size)
print(sales3.size)
print(sales4.size)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000 

Question 88: Transpose Sales Data Transpose the sales array so that:

Rows represent product categories Columns represent stores Display the new shape.

In [145]:
transpose_val=sales_data.transpose()
print(transpose_val)
print(transpose_val.shape)


[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
(6, 5)


Question 89: Combined Sales and Cost Array Stack sales_data and cost_data vertically.

Display the resulting shape.

In [146]:
sales_stack=np.vstack((sales_data,cost_data))
print(sales_stack)
print(sales_stack.shape)


[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
(10, 6)


Question 90: Store-Level Combined Data Create a three-dimensional array where:

First layer contains sales data Second layer contains cost data Use np.stack().

Display the shape of the new array.

In [158]:
three_d=np.stack((sales_data,cost_data))
print(three_d.shape)

(2, 5, 6)


Part 16: Missing Data Scenario The company discovers that some sales values were not recorded.

In [163]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

Question 91: Missing Value Detection Find:

Total number of missing values Location of missing values Stores and categories containing missing values

In [170]:
total_missing=np.isnan(sales_with_missing)
summation=np.sum(total_missing)
location=np.argwhere(total_missing)
store_name=stores[location]
category_name=categories[location]
print(total_missing)
print(summation)
print(location)
for i,j in location:
  print(stores[i],":",categories[j])
# print(store_name)

# print(store)

[[False False  True False False False]
 [False False False  True False False]
 [False False False False False False]
 [False  True False False False False]
 [False False False False  True False]]
4
[[0 2]
 [1 3]
 [3 1]
 [4 4]]
Bengaluru : Clothing
Hyderabad : Furniture
Mumbai : Groceries
Pune : Beauty


Question 92: Replace Missing Values with Zero Replace all missing sales values with zero.

In [171]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
replacing_val=np.nan_to_num(sales_with_missing,nan=0)
print(replacing_val)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 93: Replace with Company Average Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [176]:
average=round(np.nanmean(sales_with_missing),2)
replace_val=np.nan_to_num(sales_with_missing,nan=average)
print(replace_val)
     

[[ 850000.    420000.    398846.15  275000.    190000.    225000.  ]
 [ 780000.    460000.    295000.    398846.15  210000.    240000.  ]
 [ 920000.    390000.    340000.    260000.    185000.    215000.  ]
 [1050000.    398846.15  375000.    345000.    250000.    290000.  ]
 [ 690000.    405000.    280000.    225000.    398846.15  205000.  ]]


Question 94: Replace with Category Average Replace each missing value with the average sales value of its respective product category.

In [192]:
average_sales=np.nanmean(sales_with_missing,axis=0)
sales_copy=sales_with_missing.copy()
index=np.argwhere(np.isnan(sales_copy))
print(index)
for i,j in index:
  sales_copy[i,j]=average_sales[j]
print(sales_copy)

[[0 2]
 [1 3]
 [3 1]
 [4 4]]
[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


Question 95: Missing Value Impact Compare total sales before and after replacing missing values with zero.

In [197]:
sales_sum_without_replacing=np.nansum(sales_with_missing)
replacement_vals=np.nan_to_num(sales_with_missing,nan=0)
sales_sum_with_replacement=np.nansum(replacement_vals)
print(sales_sum_without_replacing)
print(sales_sum_with_replacement)
print("difference:",sales_sum_without_replacing-sales_sum_with_replacement)


10370000.0
10370000.0
difference: 0.0


Part 17: Conditional Business Decisions Question 96: Store Performance Labels Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000 "Good": Total sales between ₹24,00,000 and ₹28,00,000 "Needs Improvement": Total sales below ₹24,00,000 Use np.select().

In [198]:
sales_sum=np.sum(sales_data,axis=1)
result = np.select((sales_sum > 2800000,(sales_sum>2400000) & (sales_sum <2800000),sales_sum < 2400000),
                   ("Excellent","Good","Needs Improvement"),
                   default = "Unknow"
                   )
print(result)

['Needs Improvement' 'Needs Improvement' 'Needs Improvement' 'Excellent'
 'Needs Improvement']


Question 97: Profitability Classification Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000 "Profitable": Profit between ₹1,00,000 and ₹2,00,000 "Low Profit": Profit below ₹1,00,000 "Loss": Profit below zero

In [199]:
profit=sales_data-cost_data
result = np.select((profit > 200000,(profit>100000) & (profit <200000),profit < 100000,profit<0),
                   ("Highly Profitable","Profitable","Low Profit","Loss"),
                   default = "Unknown"
                   )
print(result)

[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


Question 98: Expansion Recommendation A store is eligible for expansion when:

Total sales are above ₹25,00,000 Total profit is above ₹7,00,000 Overall profit margin is above 25% Identify eligible stores.

In [204]:
total_profit=np.sum(sales_data-cost_data,axis=1)
total_sales=np.sum(sales_data,axis=1)
total_cost=np.sum(cost_data,axis=1)

profit_margin=(total_profit/total_sales)*100
result=((total_sales > 2500000) & (total_profit >700000)&(profit_margin >np.percentile(profit_margin,25)))
print(result)
indices=np.where(result)
print("Result:",indices)
stores_names=stores[indices]
print(stores_names)

[False False False  True False]
Result: (array([3]),)
['Mumbai']


Question 99: Category Promotion Recommendation A product category should receive additional promotion when:

Average sales are below ₹3,00,000 Profit margin is above 25% Identify the categories that satisfy these conditions.



In [216]:
average=np.mean(sales_data,axis=0)
total_profit=np.sum(sales_data-cost_data,axis=0)
total_sales=np.sum(sales_data,axis=0)

profit_margin=(total_profit/total_sales)*100
result=((average <300000)&(profit_margin>(np.percentile(profit_margin,25))))
print(result)
indices=np.where(result)
category_name=categories[indices]
print("category:",category_name)

[False False False  True  True  True]
category: ['Furniture' 'Beauty' 'Sports']


Question 100: Cost Optimization Recommendation Find store-category combinations where:

Cost is greater than ₹2,50,000 Profit margin is below 25% These combinations should be reviewed for cost optimization.

In [226]:
total_profit=sales_data-cost_data
profit_margin=(total_profit/sales_data)*100
result=((cost_data >250000)&(profit_margin <25))
indices=np.argwhere(result)
print(profit_margin)
print(result)
print(indices)
for i,j in indices:
  print(stores[i],categories[j])


[[24.70588235 25.         29.03225806 25.45454545 34.21052632 28.88888889]
 [24.35897436 23.91304348 28.81355932 27.41935484 33.33333333 29.16666667]
 [23.91304348 24.35897436 27.94117647 25.         35.13513514 27.90697674]
 [24.76190476 23.52941176 29.33333333 27.53623188 34.         29.31034483]
 [23.1884058  23.45679012 26.78571429 24.44444444 34.28571429 29.26829268]]
[[ True False False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]
 [ True  True False False False False]]
[[0 0]
 [1 0]
 [1 1]
 [2 0]
 [2 1]
 [3 0]
 [3 1]
 [4 0]
 [4 1]]
Bengaluru Electronics
Hyderabad Electronics
Hyderabad Groceries
Chennai Electronics
Chennai Groceries
Mumbai Electronics
Mumbai Groceries
Pune Electronics
Pune Groceries


Part 18: Inventory Scenario Use the following inventory arrays:

In [227]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

Question 101: Closing Stock Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [228]:
closing_stock = opening_stock - units_sold
print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification Identify store-category combinations where closing stock is below 30 units.

In [229]:
closing_stock = opening_stock - units_sold
result=closing_stock < 30
indices=np.argwhere(result)
print(indices)
for i,j in indices:
  print(stores[i],categories[j])

[[0 0]
 [0 3]
 [1 0]
 [1 3]
 [2 0]
 [2 3]
 [3 0]
 [4 0]
 [4 3]]
Bengaluru Electronics
Bengaluru Furniture
Hyderabad Electronics
Hyderabad Furniture
Chennai Electronics
Chennai Furniture
Mumbai Electronics
Pune Electronics
Pune Furniture


Question 103: Stock Availability Percentage Calculate the percentage of opening stock that remains unsold.

In [230]:
unsold=opening_stock-units_sold
result=(unsold/opening_stock)*100
print(result)

[[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


Question 104: Fast-Moving Products A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [238]:
per_opening=(units_sold/opening_stock)*100
s=np.argwhere(per_opening > 80)
print(s)
for i,j in s:
  print(stores[i],categories[j])

[[0 1]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]
 [3 0]
 [3 1]
 [3 2]
 [4 1]]
Bengaluru Groceries
Hyderabad Groceries
Hyderabad Clothing
Chennai Electronics
Chennai Groceries
Chennai Clothing
Mumbai Electronics
Mumbai Groceries
Mumbai Clothing
Pune Groceries


Question 105: Category-Wise Units Sold Calculate the total units sold for each product category.

In [242]:
total_units_sold=np.sum(units_sold,axis=0)
print(total_units_sold)

[ 485 1950 1240  345  980  720]


Question 106: Store-Wise Units Sold Calculate total units sold by each store.

In [243]:
total_units_sold=np.sum(units_sold,axis=1)
print(total_units_sold)

[1110 1175 1095 1390  950]


Question 107: Best Store by Unit Sales Identify the store that sold the highest total number of units.

In [249]:
store_names=np.sum(units_sold,axis=1)
indices=np.argmax(store_names)
print(indices)
print(stores[indices])

3
Mumbai


Question 108: Reorder Requirement A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

In [250]:
closing_stock = opening_stock - units_sold
reordering=closing_stock < 25
print(reordering)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [251]:
closing_stock=opening_stock-units_sold
result=np.where(closing_stock < 25,100-closing_stock,0)
print(result)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions Question 110: Cumulative Store Sales Calculate cumulative category sales for each store using np.cumsum().

In [252]:
cumulative_sales=np.cumsum(sales_data,axis=1)
print(cumulative_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


Question 111: Cumulative Company Sales Flatten the sales array and calculate cumulative company sales.

In [263]:
flattening=sales_data.flatten()
cumulative_sales=np.cumsum(flattening)
print(cumulative_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


Question 112: Sales Difference Between Categories Calculate the difference between consecutive category sales for each store using np.diff().

In [269]:
result=np.diff(sales_data,axis=1)
print(result)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


Question 113: Unique Sales Values Find all unique sales values in sales_data.

Also count the frequency of each value.

In [278]:
unique_vals=np.unique(sales_data)
print(unique_vals)
counting=np.unique(unique_vals,return_counts=True)
print(counting)

[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
(array([ 175000,  185000,  190000,  205000,  210000,  215000,  225000,
        240000,  250000,  260000,  275000,  280000,  290000,  295000,
        310000,  340000,  345000,  375000,  390000,  405000,  420000,
        460000,  510000,  690000,  780000,  850000,  920000, 1050000]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1]))


Question 114: Search for Specific Sales Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [284]:
result=np.argwhere(sales_data==420000)
print(result)

[[0 1]]


Question 115: Compare Sales and Cost Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [285]:
result=(sales_data > cost_data)
indices=np.argwhere(result)
print(indices)
profitabble=np.all(result)
print(profitabble)
     

[[0 0]
 [0 1]
 [0 2]
 [0 3]
 [0 4]
 [0 5]
 [1 0]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]
 [2 0]
 [2 1]
 [2 2]
 [2 3]
 [2 4]
 [2 5]
 [3 0]
 [3 1]
 [3 2]
 [3 3]
 [3 4]
 [3 5]
 [4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]
 [4 5]]
True


Question 116: Clip Profit Values For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000 Maximum: ₹2,50,000 Use np.clip() to create a reporting profit array.

In [286]:
profit=sales_data-cost_data
result=np.clip(profit,75000,250000)
print(result)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


Question 117: Normalize Sales Data Normalize all sales values using min-max normalization:

Normalized Sales = (Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

In [ ]:
normalized_sales=(sales_data - np.min(sales_data))/(np.max(sales_data - np.min(sales_data)))
print(normalized_sales)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


Question 118: Standardize Sales Data Standardize sales using:

Standardized Sales = (Sales - Mean Sales) / Standard Deviation

In [288]:
standard_sales=((sales_data - np.mean(sales_data))/(np.std(sales_data)))
print(standard_sales)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


Question 119: Round Values Convert profit margin values into:

Two decimal places Nearest whole number Floor values Ceiling values

In [307]:
total_profit=sales_data-cost_data
profit_margin=(total_profit/sales_data)*100
print(np.round(profit_margin,2))
print(np.round(profit_margin))
print(np.floor(profit_margin))
print(np.ceil(profit_margin))

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


Question 120: Save and Load Data Save the following arrays as NumPy binary files:

sales_data.npy cost_data.npy profit_data.npy Load them back and verify that the loaded arrays are equal to the original arrays.

In [309]:
profit_data=sales_data-cost_data
np.save("sales_data.npy",sales_data)
np.save("cost_data.npy",cost_data)
np.save("profit_data.npy",profit_data)
np.load("sales_data.npy")
np.load("cost_data.npy")
np.load("profit_data.npy")

array([[210000, 105000,  90000,  70000,  65000,  65000],
       [190000, 110000,  85000,  85000,  70000,  70000],
       [220000,  95000,  95000,  65000,  65000,  60000],
       [260000, 120000, 110000,  95000,  85000,  85000],
       [160000,  95000,  75000,  55000,  60000,  60000]])

In [316]:
np.load("cost_data.npy")

array([[640000, 315000, 220000, 205000, 125000, 160000],
       [590000, 350000, 210000, 225000, 140000, 170000],
       [700000, 295000, 245000, 195000, 120000, 155000],
       [790000, 390000, 265000, 250000, 165000, 205000],
       [530000, 310000, 205000, 170000, 115000, 145000]])

In [317]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])


Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


In [318]:
profit=sales_data-cost_data
profit_margin=(profit/sales_data)*100
profit_margin1=((np.sum(profit,axis=1))/(np.sum(sales_data,axis=1)))*100
target_achieved1=np.sum(sales_data>sales_targets,axis=1)
target_achieved2=np.sum(sales_data>sales_targets,axis=0)
expansion=(np.sum(sales_data,axis=1) > 2500000) & (np.sum(profit) > 700000) & (profit_margin1 > 25)
print(stores[expansion])
best=np.sum(sales_data,axis=1)
best_cost=np.sum(cost_data,axis=1)
best_cost_sales=np.max(best_cost)
worst_cost_sales=np.min(best_cost)
best_store=np.argmax(best)
worst_store=np.argmin(best)
#best profit
profit_sum=np.sum(profit,axis=1)
profit_store=np.max(profit_sum)
print(profit_store)
#best proofit margin
profit_margin_sum=np.round((np.sum(profit,axis=1))/(np.sum(sales_data,axis=1)),2)*100
best_profit_margin=np.max(profit_margin_sum)
print(stores[best_store])
print(stores[worst_store])
print(best_cost_sales)
#best category
best_category=np.sum(sales_data,axis=0)
best_category_name=np.argmax(best_category)
worst_category_name=np.argmin(best_category)
category_sum=np.sum(cost_data,axis=0)
best_category_cost=np.max(category_sum)
print(best_category)
# cateory_name=categories[best_category]
#best sales in category
sales=np.sum(sales_data,axis=0)
sales_max=np.max(sales)
#best profit category
profit_sum1=np.sum(profit,axis=0)
profit_category=np.max(profit_sum1)
#best profit margin
profit_margin_sum1=np.round((np.sum(profit,axis=0))/(np.sum(sales_data,axis=0)),2)*100
best_profit_margin_category=np.max(profit_margin_sum1)
expansion_eligibilities=()
#cost opyimization
cost_sum=np.argmax(np.sum(cost_data,axis=1))
print(cost_sum)
profit_margin0=np.max(np.sum(profit,axis=1)/(np.sum(sales_data,axis=1)))*100
#reordering
closing_stock=opening_stock-units_sold
result1=np.where(closing_stock < 25,100-closing_stock,0)
print(result1)


['Mumbai']
755000
Mumbai
Pune
2065000
[4290000 2185000 1600000 1415000 1010000 1175000]
3
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


In [319]:
closing_stock=opening_stock-units_sold
result1=np.where(closing_stock < 25,100-closing_stock,0)
print(result1)
indices=np.argwhere(closing_stock < 25)
print(indices)
for i,j in indices:
  print(stores[i],categories[j])

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]
[[4 3]]
Pune Furniture


In [337]:
print("SMART RETAIL PERFORMANCE REPORT")
print("=====================================")
print("COMPANY SUMMARY")
print("------------------------------------------")
print("Total Sales:",np.sum(sales_data))
print("Total Cost:",np.sum(cost_data))
print("Total_Profit:",np.sum(profit))
print("Profit Margin:",np.sum(profit_margin))
print("Average:",np.mean(sales_data))
print("Highest Sales:",np.max(sales_data))
print("Lowest Sales:",np.min(sales_data))
print("\nSTORE SUMMARY")
print("-------------------------------------")
print("Total Sales:",np.sum(sales_data,axis=1))
print("Total Cost:",np.sum(cost_data,axis=1))
print("Total Profit:",np.sum(profit,axis=1))
print("Profit Margin:",np.round(np.sum(profit_margin,axis=1),2))
print("No Of Targets Achieved:",target_achieved1)
print("Units Sold:",np.sum(units_sold,axis=1))
print("Expansion eligibility:",stores[expansion])
print("\nCATEGORY SUMMARY")
print("-------------------------------------")
print("Total Sales:",np.sum(sales_data,axis=0))
print("Total Cost:",np.sum(cost_data,axis=0))
print("Total Profit:",np.sum(profit,axis=0))
print("Profit Margin:",np.round(np.sum(profit_margin,axis=0),2))
print("No Of Targets Achieved:",target_achieved2)
print("Units Sold:",np.sum(units_sold,axis=0))
print("Average:",np.mean(sales_data,axis=0))
print("\nMANAGEMENT RECOMMENDATIONS")
print("=====================================")
print("\nBEST PERFORMING STORE")
print("------------------------------------------")
print("Best Store:",stores[best_store])
print("Best Sales:",np.max(best))
print("Best Cost:",best_cost_sales)
print("Best_Profit:",profit_store)
print("Best Profit Margin:",best_profit_margin)
print("\nLOWEST PERFORMING STORE")
print("---------------------------------------")
print("Worst Store:",stores[worst_store])
print("Worst Sales:",np.min(best))
print("Worst  Cost:",worst_cost_sales)
print("Worst Profit:",np.min(profit_sum1))
print("Worst Profit Margin:",np.min(profit_margin_sum1))
print("\nMOST PROFITABLE  CATEGORY")
print("---------------------------------------")
print("Best Category:",categories[best_category_name])
print("Best Sales:",np.max(best_category))
print("Best Cost:",np.max(category_sum))
print("Best Profit:",profit_category)
print("Best Profit Margin Category:",best_profit_margin_category)
print("\nWorst Profitable Category")
print("-----------------------------------------")
print("Worst Category:",categories[worst_category_name])
print("Worst Sales:",np.min(best_category))
print("Worst Cost:",np.min(category_sum))
print("Worst Profit:",np.min(profit_sum1))
print("Worst Profit Margin Category:",np.min(profit_margin_sum1))
print("\nEXPANSION RECOMMENDATIONS")
print("-----------------------------------------------")
print("Expansion Eligibilities:",stores[expansion])
print("\nCOST OPTIMIZATION")
print("-------------------------------------")
print("Store:",stores[cost_sum])
print("Category:",categories[cost_sum])
print("Cost:",np.max(np.sum(cost_data,axis=1)))
print("Profit Margin:",profit_margin0)
print("\nINVENTORY REORDER")
print("------------------------------------------")
print("Store:",stores[i])
print("Category:",categories[j])
print("Closing Stock:",closing_stock[i,j])
print("Reorder Quantity:",100-closing_stock[i,j])

SMART RETAIL PERFORMANCE REPORT
COMPANY SUMMARY
------------------------------------------
Total Sales: 11675000
Total Cost: 8600000
Total_Profit: 3075000
Profit Margin: 828.4529274527509
Average: 389166.6666666667
Highest Sales: 1050000
Lowest Sales: 175000

STORE SUMMARY
-------------------------------------
Total Sales: [2270000 2295000 2310000 2820000 1980000]
Total Cost: [1665000 1685000 1710000 2065000 1475000]
Total Profit: [605000 610000 600000 755000 505000]
Profit Margin: [167.29 167.   164.26 168.47 161.43]
No Of Targets Achieved: [1 4 2 6 0]
Units Sold: [1110 1175 1095 1390  950]
Expansion eligibility: ['Mumbai']

CATEGORY SUMMARY
-------------------------------------
Total Sales: [4290000 2185000 1600000 1415000 1010000 1175000]
Total Cost: [3250000 1660000 1145000 1045000  665000  835000]
Total Profit: [1040000  525000  455000  370000  345000  340000]
Profit Margin: [120.93 120.26 141.91 129.85 170.96 144.54]
No Of Targets Achieved: [3 2 2 2 2 2]
Units Sold: [ 485 1950 12